### ISSUE TITLE
Add WiTS Logo to navbar

### ISSUE THREAD

**Issue by MJ10** [IEEE-NITK/WiT-Summit-2018#1]
* Take the logo from the coming soon page and add to the navbar. 
* Also add it as the favicon.

**Comment by pvgupta24** [comment]
@Saharsh007 , we expect you to send a pull request and reference the issue there.
The PR should contain a proper name and a good description which mentions all the changes made in the PR and any problems that needs to be addresses.

Please submit the changes in a PR and ask for reviews.
Also ensure that you put proper commit messages.
"#1 #2 solved" doesn't give a proper overview of the changes made in a particular commit.

**Comment by Saharsh007** [comment]
I'm so sorry, will keep that in mind from now onwards. For now should I mention the change here in comment itself?

**Comment by pvgupta24** [comment]
I removed the commit.
Add the relevant commits to your fork or a new branch and send the PR by referencing the issue.

**Comment by sbshah97** [comment]
@pvgupta24 can this Issue be closed?
