### ISSUE TITLE
Update Schedule 

### ISSUE THREAD

**Issue by MJ10** [IEEE-NITK/WiT-Summit-2018#10]
Update the schedule section.

**Comment by nimbus98** [comment]
Schedule is required asap.

**Comment by MJ10** [comment]
Schedule isn't available yet. Just keep the design ready, make it dynamic, so it can read the schedule from a json file and display it

**Comment by nimbus98** [comment]
Alright, got it.

**Comment by sbshah97** [comment]
@anumehaagrawal can we close this?

**Comment by anumehaagrawal** [comment]
@nimbus98  Please update this as mentioned on the group
