### ISSUE TITLE
Add page for collaborators

### ISSUE THREAD

**Issue by pvgupta24** [IEEE-NITK/WiT-Summit-2018#22]
Add collaboration information and logos for IEEE NITK, IEEE Official, IEEE CS India SAC.
Find the logos [here](https://drive.google.com/drive/folders/1rUO8zS5XhM72_-F2TpyRWdGF5ArZfTfk).

**Comment by anumehaagrawal** [comment]
Take collaborators info from https://etheriosneo.github.io/witcomingsoon.github.io/
