### ISSUE TITLE
Add places of attractions below the venue

### ISSUE THREAD

**Issue by anumehaagrawal** [IEEE-NITK/WiT-Summit-2018#25]
Add places of attractions in a carousel - St Mary's Island , Kudremukh , malpe, gokarna, Western Ghats, Moodbidri, Murdeshwar. @pvgupta24  Please help them with the carousel

**Comment by nimbus98** [comment]
do you want the carousel to be in a new page?

**Comment by anumehaagrawal** [comment]
Nope , right below the venue

**Comment by nimbus98** [comment]
Alright cool
