### ISSUE TITLE
Fix footer

### ISSUE THREAD

**Issue by MJ10** [IEEE-NITK/WiT-Summit-2018#3]
* The footer is not formatted properly 
RePosition the social media icons
Add links to  ieee.org, ieee.nitk.ac.in, nitk.ac.

**Comment by sbshah97** [comment]
@trmittal24 you can work on this Issue as well

**Comment by trmittal24** [comment]
Okay😓

**Comment by trmittal24** [comment]
But please remove the spam from my previous commit to your Cricinfo repo!

**Comment by trmittal24** [comment]
Has Salman assigned a task to everyone to assign every issue to me?

**Comment by sbshah97** [comment]
@MJ10 I think this Issue can also be closed now?

**Comment by pvgupta24** [comment]
![screenshot from 2018-10-10 15-50-30](https://user-images.githubusercontent.com/21684823/46729906-45a5d980-cca4-11e8-8b9b-bfdb1909ddaa.png)

The footer looks weird on desktop view.
We should probably add something apart from the social buttons (and add some bottom margin as well).
@anumehaagrawal WDYT?

**Comment by sbshah97** [comment]
@MJ10 @anumehaagrawal is this done?

**Comment by anumehaagrawal** [comment]
We should probably modify it a bit. Can we add something else ?

**Comment by SamarthBonthala** [comment]
We can add links to ieee.org, ieee.nitk.ac.in, nitk.ac.in etc if possible

**Comment by sbshah97** [comment]
@anumehaagrawal please edit Issue Description and assign it to yourself!

**Comment by anumehaagrawal** [comment]
This is completed , we can close the issue
