### ISSUE TITLE
Add sponsors section

### ISSUE THREAD

**Issue by anumehaagrawal** [IEEE-NITK/WiT-Summit-2018#39]
Create a subsection with sponsors add add these logos 
Sponsors and Partners subsection

For now add:
1. IEEE Mangalore Subsection
2. IEEE Entrepreneurship
3. Intel
4. IEEE Industrial Applications Society
5. Texas Instruments
6. Simplus 

All logos search online

**Comment by SamarthBonthala** [comment]
Issue Resolved #39. Thanks for quick response
