### ISSUE TITLE
Update venue section

### ISSUE THREAD

**Issue by pvgupta24** [IEEE-NITK/WiT-Summit-2018#4]
- [x] Update the address.
- [x] Add an image in the venue section (Google and make sure that the image is compressed).
- [x] Update location in embedded google map.

Clarify in case of any doubts.

**Comment by SaurabhAgarwala** [comment]
I will also take up this...

**Comment by SaurabhAgarwala** [comment]
@pvgupta24 Which image do you want?

**Comment by SaurabhAgarwala** [comment]
I have uploaded an image matching the color scheme....please check if its fine....
