### ISSUE TITLE
Add new registration section

### ISSUE THREAD

**Issue by anumehaagrawal** [IEEE-NITK/WiT-Summit-2018#40]
Remove the registration button and create a subsection for registration and add two  subsections 
Registration for NITK delegates and link it to https://goo.gl/forms/IXihMQFwHAR2Mtgd2
Below this button add
NITK Delegate:

Registration Amount:
IEEE Members: ₹1200
Non IEEE Members: ₹1500

This amount includes Registration kit and food. Accommodation not included

Now for non nitk delegates section  create a button   name it phase two registrations and add this info below the button
Non NITK Delegate: 

Registration Amount:
IEEE CS Student Member: ₹1500
IEEE Student Member: ₹2000
Non IEEE Student Member: ₹2500
IEEE Young Professionals(with accomodation): ₹2500
IEEE Young Professionals (without accomodation): ₹2000
Non IEEE Young Professionals: ₹3000

**Comment by SamarthBonthala** [comment]
And @nimbus98 please remember to mention what the registration amount includes:

Non NITK Delegates:
Registration fee includes registration kit, food and shared accommodation in Institute hostels.

NITK Delegates:
Registration fee includes registration kit and food. Please note accommodation is not included.

**Comment by SamarthBonthala** [comment]
Good job with the new Section.

In the home page, the old Registration button and Tickets will be available soon has to be removed. @nimbus98 please make this one edit and Registration section is done.

**Comment by anumehaagrawal** [comment]
Yeah I'll make that edit

**Comment by SamarthBonthala** [comment]
Issue resolved. Thanks for the quick response #40
