### ISSUE TITLE
Add two logos to Sponsors Section

### ISSUE THREAD

**Issue by SamarthBonthala** [IEEE-NITK/WiT-Summit-2018#45]
IEEE YP and IEEE Bangalore Section Logo have to be added to the Sponsors part as requested by the sponsoring team,

![banglaore section](https://user-images.githubusercontent.com/20479421/49302529-6133a080-f4ed-11e8-9eed-85dfe0853e54.jpg)
![yp-blr logo](https://user-images.githubusercontent.com/20479421/49302531-6133a080-f4ed-11e8-9261-2a6837e83453.png)

**Comment by nimbus98** [comment]
On it

**Comment by nimbus98** [comment]
Okay, nevermind, its already done xD

**Comment by SamarthBonthala** [comment]
Issue resolved #45
