### ISSUE TITLE
New Speaker - Mr. Abhishek M Appaji

### ISSUE THREAD

**Issue by SamarthBonthala** [IEEE-NITK/WiT-Summit-2018#47]
![abhishek_headshot_photo](https://user-images.githubusercontent.com/20479421/49330781-9279a280-f5b9-11e8-9b9c-852141d6f552.jpg)
Add to Speaker list on Website.
Name: Abhishek M Appaji
Mention his description as "YP Chair, IEEE Bangalore Section"

**Comment by anumehaagrawal** [comment]
@SaurabhAgarwala  Please work on this

**Comment by SamarthBonthala** [comment]
Issue Resolved #47
