### ISSUE TITLE
Adding NITK and NITK IEEE logo

### ISSUE THREAD

**Issue by SamarthBonthala** [IEEE-NITK/WiT-Summit-2018#49]
On cover section of the website, towards the right side can we add NITK logo and NITK IEEE logo.
Top: NITK logo
Below the NITK logo: NITK IEEE logo

Change requested by sir.
![image](https://user-images.githubusercontent.com/20479421/49337134-69e2be80-f634-11e8-9e6c-8a06b9a7300b.png)

**Comment by SamarthBonthala** [comment]
Add the logos side by side also its fine. I mean right aligned logos

**Comment by sbshah97** [comment]
@SamarthBonthala has this been done?

**Comment by SamarthBonthala** [comment]
Yes it's completed
