### ISSUE TITLE
Update FAQ

### ISSUE THREAD

**Issue by MJ10** [IEEE-NITK/WiT-Summit-2018#5]
Update the FAQ with the actual content.

**Comment by sbshah97** [comment]
@mj10 I believe this Issue can be closed?

**Comment by anumehaagrawal** [comment]
@salman-bhai  Not yet , We might need to add more FAQ's

**Comment by sbshah97** [comment]
@MJ10 @anumehaagrawal shall we close this?

**Comment by anumehaagrawal** [comment]
@SamarthBonthala  Do we need any more FAQ's ?

**Comment by SamarthBonthala** [comment]
Yes I guess we need more FAQs. You can assign Daphne to work on the content. @anumehaagrawal
