### ISSUE TITLE
Updating Student Team Section

### ISSUE THREAD

**Issue by SamarthBonthala** [IEEE-NITK/WiT-Summit-2018#53]
We need to add from where each person is along with their name and post so that we can say ours is an all India event

A new name has to be added 
Karthik K
CS India SAC Volunteer, Kerala Section
Sponsorship Team Lead

Sailakshmi P V
Kerala Section Young Professional
WiTS Co-Ordinator

Neeraj V Ipe - CS India SAC Volunteer, Kerala Section
Abdul Halik - CS India SAC Volunteer, Madras Section
Afnan Nazer - CS India SAC Volunteer, Kerala Section
Saikrishna V - CS India SAC Volunteer, Kerala Section
Mohd Sharif - Hyderabad Section YP

For all NITK Students we can write, NITK IEEE Volunteer, Bangalore Section

![image](https://user-images.githubusercontent.com/20479421/49356791-ecca4e80-f6f2-11e8-9211-4dde30c76df6.png)

**Comment by anumehaagrawal** [comment]
Also add Daphne - Content Lead

**Comment by SamarthBonthala** [comment]
Daphne Jenson
IEEE CS India SAC Volunteer, Madras Section
Documentation Lead

Thanks for reminding @anumehaagrawal

**Comment by mahim23** [comment]
@SamarthBonthala @anumehaagrawal Should the two new names be added at the end of the current list? Or in some other order?

**Comment by SamarthBonthala** [comment]
End of current list

**Comment by SamarthBonthala** [comment]
Add it before the track leads. That would be sufficient
