### ISSUE TITLE
Add speakers the Speaker Section of Website 

### ISSUE THREAD

**Issue by SamarthBonthala** [IEEE-NITK/WiT-Summit-2018#56]
Please add the following Speakers
Muktha Hiremath
![muktha_pic](https://user-images.githubusercontent.com/20479421/49563025-ff879200-f943-11e8-8b5c-80900c70fb0d.jpg)

Monisha Pattanaik
![monisha](https://user-images.githubusercontent.com/20479421/49563044-0f9f7180-f944-11e8-9592-af75265c0963.jpg)

Aparna Kongot
![aparna](https://user-images.githubusercontent.com/20479421/49563060-1e862400-f944-11e8-92d9-5df5b8a33635.jpg)

For everyone company mention as "SAP Labs"

**Comment by anumehaagrawal** [comment]
This is done , we can close the issue

**Comment by SamarthBonthala** [comment]
Thanks @anumehaagrawal. I am closing the issue now.
