### ISSUE TITLE
Styling changes

### ISSUE THREAD

**Issue by pvgupta24** [IEEE-NITK/WiT-Summit-2018#6]
- [x] Change the colour scheme for the website.
- [x] Compress the [background image](https://ieee.nitk.ac.in/WiT-Summit-2018/img/girl.svg) to the required size and make the image non-scrollable.

**Comment by sbshah97** [comment]
@pvgupta24 can we close this Issue?

**Comment by pvgupta24** [comment]
> Compress the background image to the required size and make the image non-scrollable.

@nimbus98 , you had updated this right? Did you revert back to the previous image as the image is still scrollable on the [website](https://ieee.nitk.ac.in/WiT-Summit-2018/).

**Comment by nimbus98** [comment]
I had made it unscrollable, but I think someone made it scrollable again.
I think Anumeha, but I'm not sure.
Sorry about the late reply.

**Comment by sbshah97** [comment]
Can you check the commit history and revert back to the old code @nimbus98 ?

**Comment by nimbus98** [comment]
I can make it unscrollable again if you want, its a matter of three lines of code in the css file, no issue.

**Comment by sbshah97** [comment]
@pvgupta24 can we close this?
