### ISSUE TITLE
Please add the following details to the speakers' section. 

### ISSUE THREAD

**Issue by adwait1-g** [IEEE-NITK/WiT-Summit-2018#65]
There are 2 speakers from DELL. The following are the details. 

Speaker1: 

<img width="744" alt="profile" src="https://user-images.githubusercontent.com/22262158/49787226-2aab2080-fd4c-11e8-8d9f-d8230c4d1725.png">

Speaker2: 
![sheenam ohrie](https://user-images.githubusercontent.com/22262158/49787356-7d84d800-fd4c-11e8-9218-f2c1fbbec4db.jpg)

Details of Speaker2: 

**Sheenam Ohrie 
Vice President – Enterprise Data Mobility And Engineering CIO Leader, Dell India**
Sheenam Ohrie is the Vice President for Enterprise Data & Mobility Engineering at Dell. She also plays the role of an APJ CIO Leader and is Chairperson for Women in Action chapter for Dell India.
Currently based in Bangalore, Sheenam has more than 25 years of experience in various aspects of global delivery, product management, testing and leadership roles.  She is a versatile and strategic IT leader. Experienced in information risk management, she applies systemic and broad business perspective to IT programs. She has proven record of conceptualizing and delivering technology solutions in line with organizational needs. She has expertise in diverse & multicultural global team building, strong networking, partner relationship management and team motivation.
At Dell, Sheenam is responsible for the Enterprise Applications implementation and support, Data and Analytics and Mobility Engineering. Her vision is to transform the IT delivery into a Digital IT-as-a-Service business model through a combination of platforms, products and services.
Prior to joining Dell, Sheenam has worked with EdgeVerve, Infosys, SAP, Oracle Financial Services Ltd. (erstwhile i-flex solutions Ltd.) and Business Objects. She has received various certificates and accreditations including SAFE Agilist certification, Design Thinking Facilitator, LEAN Coach, PCC Executive Coach and Erickson PCC coach certification. She is a catalytic thinker and has coached over 50 leaders.
She was recently awarded as Global IT Leader of the Year by IWLF.

**Comment by anumehaagrawal** [comment]
@Saharsh007 Have you added these as well ?
