### ISSUE TITLE
Integrating Payment Gateway 

### ISSUE THREAD

**Issue by MJ10** [IEEE-NITK/WiT-Summit-2018#7]

**Comment by sbshah97** [comment]
@mahim23 any updates on this?

**Comment by mahim23** [comment]
@salman-bhai there was change of plans regarding the payment gateway and its still not finalized.

**Comment by sbshah97** [comment]
@SamarthBonthala @anumehaagrawal shall we close this?

**Comment by anumehaagrawal** [comment]
Yeah we can
