### ISSUE TITLE
Add Photo to Sponsors Section

### ISSUE THREAD

**Issue by SamarthBonthala** [IEEE-NITK/WiT-Summit-2018#71]
Please note, this photo has to go to Sponsors section and not Speakers section.

Mr. A S Karanth
KREC Alumni 1970, EEE Department

![a s karanth 1970ee krec](https://user-images.githubusercontent.com/20479421/49979414-e2227b80-ff74-11e8-9c21-4be24560dc01.jpg)

A line can also be added at the beginning of the Sponsors section. "Thank You Sponsors for your valuable contribution aiding us in successfully conducting this event."

**Comment by Saharsh007** [comment]
@SamarthBonthala  asked to hold on this issue for now.

**Comment by sbshah97** [comment]
Any updates on this issue?

**Comment by SamarthBonthala** [comment]
Yeah go ahead adding this photo to the Financial Sponsors section
