### ISSUE TITLE
Change Pages

### ISSUE THREAD

**Issue by pvgupta24** [IEEE-NITK/WiT-Summit-2018#8]
Remove the following pages from the navbar and delete the unrequired files : 
- [x] Livestream
- [x] Tickets

Add a `Team` page with the details of all collaborating organizations;
- [ ] IEEE NITK
- [ ] IEEE Mangalore Subsection
- [ ] IEEE CS India SAC

**Comment by sbshah97** [comment]
@trmittal24 you can resolve this as Hacktoberfest work :stuck_out_tongue:

**Comment by trmittal24** [comment]
Okay 😪

**Comment by sbshah97** [comment]
@mj10 any update on this Issue?
