### ISSUE TITLE
[Low priority] Beautify Partners section

### ISSUE THREAD

**Issue by sagar-bharadwaj-ks** [IEEE-NITK/WiT-Summit-2018#84]
The "Partners" section looks, for want of a better word, crass :p
Probably reduce the size of logos a little bit? Idk!

We'll have to show all sponsors that we have put up their logos on the website. So better if it's beautiful :|

**Comment by sbshah97** [comment]
@anumehaagrawal are we done on this one?

**Comment by anumehaagrawal** [comment]
@salman-bhai  yeah we are
