### ISSUE TITLE
[Medium Priority] Change order of logos for financial sponsorship. Also put the subsection above technical sponsorship.

### ISSUE THREAD

**Issue by sagar-bharadwaj-ks** [IEEE-NITK/WiT-Summit-2018#85]
Let's put all the logos in "Financial Sponsorship" section in the order of sponsorship amount!

![spnsorship banner - copy](https://user-images.githubusercontent.com/19309411/50094136-72441780-0238-11e9-923b-4fdd64b8523f.jpg)

**Comment by anumehaagrawal** [comment]
@nimbus98 Whats the status on this ?

**Comment by nimbus98** [comment]
Sorry about that
Its done.
