### ISSUE TITLE
[Very Very High Priority] Update Schedule on Website

### ISSUE THREAD

**Issue by SamarthBonthala** [IEEE-NITK/WiT-Summit-2018#86]
Rename the Schedule which is presently Tentative Schedule and add the content of this document there.
[WiTS_Schedule.pdf](https://github.com/IEEE-NITK/WiT-Summit-2018/files/2691750/WiTS_Schedule.pdf)

**Comment by anumehaagrawal** [comment]
Sorry just saw this issue , will do it right away

**Comment by anumehaagrawal** [comment]
This is done @SamarthBonthala . Let me know if there are more changes needed

**Comment by sbshah97** [comment]
@SamarthBonthala close the Issue if no changes are required!
